---
name: "Linting"

on:
  push:
    branches:
      - "*"

env:
  GO_VERSION: "1.23.x"

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          github-token: "${{ github.token }}"
          working-directory: env
          version: v1.58.2
