---
name: "Testing"

on:
  push:
    branches:
      - "*"

env:
  GO_VERSION: "1.23.x"

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Run tests
        run: go test ./...
